from __future__ import annotations
import json
import time
from pathlib import Path
import glob


def _read_snippet(path: Path, max_chars: int = 1600) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return "(unavailable)"
    if len(text) <= max_chars:
        return text.strip()
    return text[: max_chars].rstrip() + "\n\n… (truncated)"


def _latest_glob(pattern: str) -> Path | None:
    matches = glob.glob(pattern)
    if not matches:
        return None
    matches_sorted = sorted(matches)
    return Path(matches_sorted[-1])


def build_context_pack(root: Path) -> Path:
    attachments = root / "Copilot_Attachments"
    attachments.mkdir(parents=True, exist_ok=True)
    out = attachments / "ContextPack_Current.md"

    lines: list[str] = []
    ts = time.strftime("%Y-%m-%d %H:%M:%S")

    # Header
    lines.append("# AI_Coder_Controller – Context Pack (Current)")
    lines.append("")
    lines.append(f"Generated: {ts}")
    lines.append(f"Workspace root: {root}")
    lines.append("")

    # Guidance for Copilot / consuming agents
    lines.append("## How this file should be used")
    lines.append("")
    lines.append("This markdown file is generated by the AI_Coder_Controller workflow.")
    lines.append("It is intended to be attached or pasted into Copilot or other agents so they")
    lines.append("have a compact, linked summary of the current project, objectives, and recent runs.")
    lines.append("")
    lines.append("When you (Copilot) read this file:")
    lines.append("- Follow the markdown links to inspect specific files as needed.")
    lines.append("- Refer to files by their paths when proposing edits.")
    lines.append("- Use objective/config sections to infer intent before suggesting changes.")
    lines.append("")

    # Project overview / README
    readme = root / "README.md"
    lines.append("## Project overview")
    lines.append("")
    if readme.exists():
        lines.append(f"Primary overview: [README.md](README.md)")
        lines.append("")
        snippet = _read_snippet(readme, max_chars=1400)
        if snippet:
            lines.append("### README excerpt")
            lines.append("")
            lines.append("```text")
            lines.append(snippet)
            lines.append("```")
            lines.append("")
    else:
        lines.append("README.md not found in workspace root.")
        lines.append("")

    # Objectives and policy
    lines.append("## Objectives and policy")
    lines.append("")
    cfg_dir = root / "config"
    objective_files: list[Path] = []
    for name in ["objectives.md", "objectives_orchestrator.md", "objectives_test.md"]:
        p = cfg_dir / name
        if p.exists():
            objective_files.append(p)
    if objective_files:
        for obj in objective_files:
            rel = obj.relative_to(root)
            lines.append(f"### {rel}")
            lines.append("")
            lines.append(f"Path: [{rel}]({rel})")
            lines.append("")
            snippet = _read_snippet(obj, max_chars=1200)
            if snippet:
                lines.append("```markdown")
                lines.append(snippet)
                lines.append("```")
                lines.append("")
    else:
        lines.append("No objectives*.md files found under config/.")
        lines.append("")

    policy = cfg_dir / "policy_rules.json"
    if policy.exists():
        lines.append("### config/policy_rules.json (excerpt)")
        lines.append("")
        try:
            raw = policy.read_text(encoding="utf-8")
            rules = json.loads(raw)
        except Exception:
            rules = None
        if isinstance(rules, dict):
            # Highlight a few relevant sections instead of dumping full JSON
            focus_keys = ["bounds", "copilot", "workflow", "agent", "phi4"]
            subset = {k: rules.get(k) for k in focus_keys if k in rules}
            lines.append("```json")
            try:
                lines.append(json.dumps(subset, indent=2))
            except Exception:
                lines.append(_read_snippet(policy, max_chars=1200))
            lines.append("```")
        else:
            lines.append("```json")
            lines.append(_read_snippet(policy, max_chars=1200))
            lines.append("```")
        lines.append("")

    orch_cfg = cfg_dir / "vscode_orchestrator.json"
    if orch_cfg.exists():
        lines.append("### config/vscode_orchestrator.json (excerpt)")
        lines.append("")
        lines.append("```json")
        lines.append(_read_snippet(orch_cfg, max_chars=1200))
        lines.append("```")
        lines.append("")

    # Structure inventories / attachments
    lines.append("## Project structure inventories (attachments)")
    lines.append("")
    fs_inventory_files = sorted([p for p in attachments.glob("*_fs_structure.txt") if p.is_file()])
    if fs_inventory_files:
        for inv in fs_inventory_files:
            rel = inv.relative_to(root)
            lines.append(f"- [{rel}]({rel})")
        lines.append("")
    else:
        lines.append("No *_fs_structure.txt inventory files found in Copilot_Attachments/.")
        lines.append("")

    # Agent Mode module inventory
    agent_inv = attachments / "AgentModeModules.txt"
    if agent_inv.exists():
        rel = agent_inv.relative_to(root)
        lines.append("## Agent Mode modules and configs")
        lines.append("")
        lines.append(f"Inventory: [{rel}]({rel})")
        lines.append("")
        snippet = _read_snippet(agent_inv, max_chars=1600)
        if snippet:
            lines.append("```text")
            lines.append(snippet)
            lines.append("```")
            lines.append("")

    # Recent workflow summary
    lines.append("## Recent Test/Gather/Assess workflow (if any)")
    lines.append("")
    latest_summary = _latest_glob(str(root / "logs/tests/workflow_summary_*.json"))
    if latest_summary and latest_summary.exists():
        rel = latest_summary.relative_to(root)
        lines.append(f"Latest workflow summary: [{rel}]({rel})")
        try:
            obj = json.loads(latest_summary.read_text(encoding="utf-8"))
        except Exception:
            obj = None
        if isinstance(obj, dict):
            overall = bool(obj.get("pass", False))
            steps = obj.get("steps") or []
            lines.append("")
            lines.append(f"- Overall status: {'PASS' if overall else 'FAIL'}")
            lines.append(f"- Steps recorded: {len(steps)}")
            errs = obj.get("errors") or []
            lines.append(f"- Error entries: {len(errs)}")
        lines.append("")
    else:
        lines.append("No workflow_summary_*.json found under logs/tests/ yet.")
        lines.append("")

    # OCR observation report (if present)
    lines.append("## OCR / assessment reports (if any)")
    lines.append("")
    ocr_md = _latest_glob(str(root / "Archive_OCR_Images_Assessments/OBSERVED_OCR_IMAGES_*.md"))
    if ocr_md and ocr_md.exists():
        rel = ocr_md.relative_to(root)
        lines.append(f"Latest OCR assessment report: [{rel}]({rel})")
        lines.append("")
    else:
        lines.append("No OBSERVED_OCR_IMAGES_*.md assessment reports found yet.")
        lines.append("")

    # Key implementation entry points
    lines.append("## Key implementation entry points")
    lines.append("")
    key_files: list[tuple[str, str]] = [
        ("src/main.py", "Main controller, Agent Mode loop, wiring of capture/control/ocr/orchestrator."),
        ("src/agent_terminal.py", "TerminalAgent – single gateway for VS Code integrated terminal commands."),
        ("src/messaging.py", "CopilotMessenger – routes messages to Copilot app or VS Code chat, uses OCR for readback."),
        ("src/vsbridge.py", "VSBridge – automation bridge for VS Code windows, chat, and terminal."),
        ("src/windows.py", "WindowsManager – foreground window discovery and focus helpers."),
        ("src/ocr.py", "CopilotOCR – OCR configuration and capture routines."),
        ("src/self_improve.py", "Self-improvement helpers and metadata writers."),
        ("src/ui.py", "App UI, hotkeys, and control window."),
        ("src/policy.py", "Policy/action definitions driven by config/policy_rules.json."),
        ("src/vscode_automation", "VS Code multi-window orchestrator and chat keepalive components."),
        ("Scripts/workflow_test_gather_assess.py", "End-to-end Test/Gather/Assess workflow runner."),
    ]
    for rel_str, desc in key_files:
        p = root / rel_str
        if p.exists():
            rel = p.relative_to(root)
            lines.append(f"- [{rel}]({rel}) – {desc}")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    try:
        out = build_context_pack(root)
        print(f"Context pack written to {out}")
        return 0
    except KeyboardInterrupt:
        return 1
    except Exception as e:
        # Fail closed but do not raise; this is often a best-effort step.
        print(f"Failed to build context pack: {e}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
